//! Embeds the application icon into the executable.
//!
//! Without this the .exe carries no `RT_GROUP_ICON` at all, so Windows falls back to the
//! generic application icon in the taskbar, Alt+Tab and Explorer.
//!
//! This drives the Windows SDK resource compiler directly rather than adding a build
//! dependency. `rc.exe` ships with the Visual Studio build tools that a Windows Rust
//! toolchain already needs for linking, so it is normally present; if it cannot be found
//! the build still succeeds, just icon-less, with a `cargo:warning` explaining why.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=app.rc");
    println!("cargo:rerun-if-changed=../../assets/a2ahandoff.ico");

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    // Walk up to the workspace root rather than joining "..": `canonicalize()` would
    // return a \\?\ extended-length path, and rc.exe mangles the `\\?\` prefix into
    // "file not found". These paths are already absolute, so no canonicalisation is
    // needed and no `..` reaches the resource compiler.
    let workspace = manifest
        .parent()
        .and_then(Path::parent)
        .unwrap_or(&manifest);
    let ico = workspace.join("assets").join("a2ahandoff.ico");
    if !ico.exists() {
        println!(
            "cargo:warning={} is missing; building without an icon",
            ico.display()
        );
        return;
    }

    let Some(rc) = find_rc() else {
        println!(
            "cargo:warning=rc.exe not found (Windows SDK / VS build tools); \
             building without an application icon"
        );
        return;
    };

    // A stable absolute path, so the resource compiler resolves the icon regardless of
    // the working directory cargo happens to use. Written with FORWARD slashes: rc.exe
    // treats backslashes inside the quoted path as escapes, turning `\T` into a tab and
    // `\a` into a bell, then fails with a mangled "file not found".
    let ico_rc_path = ico.display().to_string().replace('\\', "/");
    let rc_file = manifest.join("app.rc");
    std::fs::write(
        &rc_file,
        format!(
            "// Generated by build.rs - edited automatically, do not hand-edit.\n\
             // IDI_APPICON = 1: the lowest icon id, which Explorer and the taskbar pick.\n\
             #define IDI_APPICON 1\n\
             IDI_APPICON ICON \"{}\"\n",
            ico_rc_path
        ),
    )
    .expect("write app.rc");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let res = out_dir.join("app.res");
    let status = Command::new(&rc)
        .arg("/nologo")
        .arg("/fo")
        .arg(&res)
        .arg(&rc_file)
        .status();

    match status {
        Ok(s) if s.success() && res.exists() => {
            println!("cargo:rustc-link-arg={}", res.display());
        }
        Ok(s) => println!("cargo:warning=rc.exe exited with {s}; building without an icon"),
        Err(e) => println!("cargo:warning=could not run rc.exe ({e}); building without an icon"),
    }
}

/// Locate `rc.exe`: first on PATH, then by walking the Windows SDK bin tree, preferring
/// the newest version and this machine's architecture.
fn find_rc() -> Option<PathBuf> {
    if let Ok(out) = Command::new("where").arg("rc.exe").output() {
        if out.status.success() {
            let text = String::from_utf8_lossy(&out.stdout);
            if let Some(first) = text.lines().map(str::trim).find(|l| !l.is_empty()) {
                let p = PathBuf::from(first);
                if p.exists() {
                    return Some(p);
                }
            }
        }
    }

    let arch = std::env::consts::ARCH;
    let arch_dir = match arch {
        "x86_64" => "x64",
        "aarch64" => "arm64",
        _ => "x86",
    };
    let roots = [
        std::env::var("ProgramFiles(x86)").ok(),
        std::env::var("ProgramFiles").ok(),
    ];
    let mut candidates: Vec<PathBuf> = Vec::new();
    for root in roots.into_iter().flatten() {
        let base = Path::new(&root).join("Windows Kits/10/bin");
        let Ok(versions) = std::fs::read_dir(&base) else {
            continue;
        };
        for v in versions.flatten() {
            let p = v.path().join(arch_dir).join("rc.exe");
            if p.exists() {
                candidates.push(p);
            }
        }
    }
    // Newest SDK first: the version directory names sort lexicographically by date.
    candidates.sort();
    candidates.pop()
}
